FizzBuzz.Web/Models/FizzBuzzModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using X.PagedList;

namespace FizzBuzz.Web.Models
{
    public class FizzBuzzModel
    {
        [Required(ErrorMessage = "Please enter the number")]
        [Range(1, 1000, ErrorMessage = "Enter Number between 1 to 1000")]
        [Display(Description = "Please enter the number")]

        public int Number { get; set; }

        public IPagedList<String> Result { get; set; }
    }
}

FizzBuzz.Web/Controllers/FizzBuzzController.cs
using FizzBuzz.Business.Interfaces;
using FizzBuzz.Web.Models;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace FizzBuzz.Web.Controllers
{
    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzManager FizzBuzz;
        public FizzBuzzController(IFizzBuzzManager FizzBuzz)
        {
            this.FizzBuzz = FizzBuzz;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View("Index");
        }

        [HttpGet]
        public ActionResult GetNextPage(FizzBuzzModel ticTacModel, int? page)
        {
            var resultList = this.FizzBuzz.GetFizzBuzzList(ticTacModel.Number);
            ticTacModel.Number = ticTacModel.Number;
            ticTacModel.Result = resultList.ToPagedList(page ?? 1, 20);
            return View("Index", ticTacModel);
        }

        [HttpPost]
        public ActionResult Index(FizzBuzzModel model, int? page)
        {
            if(!ModelState.IsValid)
            {
                return View("Index");
            }
            model.Result = this.FizzBuzz.GetFizzBuzzList(model.Number).ToPagedList(page ?? 1, 20);
            return this.View("Index",model);
        }
    }
}

FizzBuzz.Web/Views/FizzBuzz/Index.cshtml
@model FizzBuzz.Web.Models.FizzBuzzModel
@using Microsoft.AspNetCore.Html;
@using FizzBuzz.Web.Helper;
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@{
    ViewBag.Title = "Index";
}
<h2>FizzBuzzApplication</h2>

@using (Html.BeginForm("Index", "FizzBuzz", FormMethod.Post))
{
    @Html.LabelFor(model => model.Number)
    @Html.TextBoxFor(model => model.Number)
    @Html.ValidationMessageFor(model => model.Number)
    <input type="submit" value="submit" />
}
<div>
    @if (Model != null && Model.Result != null)
    {
        foreach (var i in Model.Result)
        {
            @Html.RenderTicTacList(i) <br />
        }
    }
</div>
<div class="X.PagedList">
    @if (Model != null && Model.Result != null)
    {
        @Html.PagedListPager(Model.Result, page => Url.Action("GetNextPage", "FizzBuzz", new { Number = Model.Number, page }))
    }
</div>

FizzBuzz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FizzBuzz.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/FizzBuzzColor.css" />
    <link rel="stylesheet" href="~/css/X.PagedList.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FizzBuzz.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FizzBuzz.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>